Profiles for TPV and Dune HD homatics. New Apps 1und1 TV and Arte and special Apps for TPV (Philips) TV
unfoldedcircle/integration-androidtv pull request #43
Opened 2024-04-22 06:56 UTC by Kat-CeDe

Profiles for the devices Dune HD Homatics Box R 4K Plus and TPV (Philips) AndroidTV TVs
In my eyes the special Apps for TPV TV are the most interesting changes.

2024-04-29 07:01 UTC, zehnm requested changes
Cool, thanks for the additional profiles!
Please fix the linting issue and the CHANGELOG, then I'll merge it and create a new release.

2024-04-29 07:01 UTC, zehnm commented on intg-androidtv/apps.py
Linting issue: https://github.com/unfoldedcircle/integration-androidtv/pull/43/checks

Probably missing comma in line 80

2024-04-29 07:45 UTC, zehnm commented on intg-androidtv/apps.py
There's still an issue: 

https://github.com/unfoldedcircle/integration-androidtv/actions/runs/8874808081/job/24362930301?pr=43#step:7:12

You can check & format the code locally with Black: https://github.com/unfoldedcircle/integration-androidtv/blob/main/docs/code_guidelines.md#format-code

2024-04-30 11:18 UTC, zehnm requested changes

2024-04-30 11:18 UTC, zehnm commented on intg-androidtv/apps.py
> + }
Linting issue https://github.com/unfoldedcircle/integration-androidtv/actions/runs/8891314506/job/24413032213?pr=43

You can check & format the code locally with Black: https://github.com/unfoldedcircle/integration-androidtv/blob/main/docs/code_guidelines.md#format-code

Most IDEs allow to configure "save-actions" to always format the code when it's saved.

2024-04-30 12:28 UTC, Kat-CeDe commented
I tried to add black code to GitHub and got the recommendation to add this. Before I used black code on windows with VS code but this formated completely different than yours.

Ralf Biedermann

----
Die Lücke, die ich hinterlasse, ersetzt mich vollständig!

RBsoft
----
----------------------------------------

30.04.2024 13:18:33 Markus Zehnder ***@***.***>:

> 
> ***@***.**** requested changes on this pull request.
> 
> ----------------------------------------
> 
> In .github/ISSUE_TEMPLATE/config.yml[https://github.com/unfoldedcircle/integration-androidtv/pull/43#discussion_r1584570602]:
> 
>> +  - name: Black Code Formatter
> +    uses: ***@***.***
> 
> What is that for?
> 
> ----------------------------------------
> 
> In intg-androidtv/apps.py[https://github.com/unfoldedcircle/integration-androidtv/pull/43#discussion_r1584607475]:
> 
>> @@ -22,7 +22,16 @@
>      "ARD Mediathek": {"url": "https://www.ardmediathek.de/"},
>      "ZDF Mediathek": {"url": "https://www.zdf.de/filme"},
>      "Kodi": {"url": "market://launch?id=org.xbmc.kodi"},
> -}
> +    "1und1": {"url": "1und1tv://1und1.tv"},
> +    "Arte": {"url": "arte://display"},
> +    "Google Play Store": {"url": "https://play.google.com/store/"},
> +    "DVB-C/T/S": {"url": "market://launch?id=org.droidtv.playtv"},
> +    "ATV Inputs": {"url": "market://launch?id=org.droidtv.channels"},
> +    "ATV PlayFI": {"url": "market://launch?id=com.phorus.playfi.tv"},
> +    "ATV Now on TV": {"url": "market://launch?id=org.droidtv.nettvrecommender"},
> +    "ATV Media": {"url": "market://launch?id=org.droidtv.contentexplorer"},
> +    "ATV Browser": {"url": "market://launch?id=com.vewd.core.browserui"},
> + }
> 
> Linting issue https://github.com/unfoldedcircle/integration-androidtv/actions/runs/8891314506/job/24413032213?pr=43
> 
> You can check & format the code locally with Black: https://github.com/unfoldedcircle/integration-androidtv/blob/main/docs/code_guidelines.md#format-code
> 
> Most IDEs allow to configure "save-actions" to always format the code when it's saved.
> 
> —
> Reply to this email directly, view it on GitHub[https://github.com/unfoldedcircle/integration-androidtv/pull/43#pullrequestreview-2030938838], or unsubscribe[https://github.com/notifications/unsubscribe-auth/AA2KRKN75YMMSQREJBDU6ATY754YLAVCNFSM6AAAAABGSFKLQ6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMZQHEZTQOBTHA].
> You are receiving this because you authored the thread.
> [Verfolgungsbild][https://github.com/notifications/beacon/AA2KRKOTWPWVX7K2BB5XQX3Y754YLA5CNFSM6AAAAABGSFKLQ6WGG33NNVSW45C7OR4XAZNRKB2WY3CSMVYXKZLTORJGK5TJMV32UY3PNVWWK3TUL5UWJTTZBWVNM.gif]
>

2024-04-30 15:54 UTC, zehnm commented
> I tried to add black code to GitHub and got the recommendation to add this.

Please restore `.github/ISSUE_TEMPLATE/config.yml` in the pull request.
If you enable GitHub actions in your repository, then the same checks are run on each push.

> Before I used black code on windows with VS code but this formated completely different than yours.

You can use the command line as described here: https://github.com/unfoldedcircle/integration-androidtv/blob/main/docs/code_guidelines.md#tooling

2024-05-01 18:35 UTC, zehnm commented
Please fix the linting issue if you get a chance.
All checks must be successful to merge a PR.

2024-05-06 12:45 UTC, zehnm approved these changes
All good now and thanks again for the PR!
I'll create a new release soon and include it in the next beta firmware.

2024-05-06 12:46 UTC, merged